[project]
name = "chomsky_vv"
version = "0.1.0"
dependencies = ["pydantic>=2.7"]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pytest>=8.0",
    "ruff>=0.11.7",
]

[tool.setuptools]
packages = { find = { include = ["chomsky_vv", "chomsky_vv.*"] } }

[tool.setuptools.package-data]
chomsky_vv = ["py.typed"]

[build-system]
requires = ["setuptools<78.0.0", "wheel"]
build-backend = "setuptools.build_meta"
